bitbake_target: helloworld-empty
configuration_name: pyro
bitbake_ref: 1.34
oecore_ref: pyro
localconf: |
  LICENSE_FLAGS_WHITELIST = "commercial"
  SUPPORTED_RECIPES_CHECK = ""
dependencies:
  - url: git://git.openembedded.org/meta-openembedded
    ref: pyro
    layers:
      - meta-oe
